apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-webapp
  name: test-webapp
spec:
  containers:
  - image: shahbazmahmood123/cluster-test:0.3
    ports:
    - containerPort: 8000
    name: test-webapp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: test-webapp
  name: test-webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: NodePort
  selector:
    run: test-webapp
status:
  loadBalancer: {}
